<?php

namespace AppBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllStudents($convocatory = null)
    {
        return $this->findAll();
    }

    public function getAllStudentsConvocatory($convocatory)
    {
        return $this->findBy(Array("convocatory" => $convocatory));
    }

    public function getAllStudentsConvocatoryExento($convocatory, $type)
    {
        if ($type == 'company'){
            $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Student', 't')
            ->where('t.convocatory = :convocatory_id')
            ->andwhere('t.fctexento = 0')
            ->setParameter('convocatory_id', $convocatory);
        }else{
             $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Student', 't')
            ->where('t.convocatory = :convocatory_id')
            ->andwhere('t.piexento = 0')
            ->setParameter('convocatory_id', $convocatory);
        }
       
        return $qb->getQuery()->getResult();
    }

    public function getAllStudentsNoDistribution($convocatory, $type)
    {
        $control= "";
        $table = "";
        if ($type == 'company'){
            $table = 'AppBundle:Distribution_company';
            $control ="1";
        }else{
            $table = 'AppBundle:Distribution_project';
            $control ="2";
        }

        $q2b = $this->getEntityManager()->createQueryBuilder()
                    ->select('st.id')
                    ->from($table, 'd')
                    ->join('d.student', 'st');


        $arrayIds = $this->arrayIdsToString($q2b->getQuery()->getArrayResult());

        if (count($arrayIds) > 0)
            return $this->getStudentsNotIN($convocatory, $arrayIds,$control);
        return $this->getAllStudentsConvocatory($convocatory);
    }

    public function getStudentsNotIN($convocatory, $arrayIds,$control)
    {
        if ($control== "1") {
            $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Student', 't')
            ->where('t.convocatory = :convocatory_id')
            ->andwhere('t.fctexento = 0')
            ->andWhere('t.id NOT IN(' . implode(",", $arrayIds) . ')')
            ->setParameter('convocatory_id', $convocatory);
        }else{
            $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t')
            ->from('AppBundle:Student', 't')
            ->where('t.convocatory = :convocatory_id')
            ->andwhere('t.piexento = 0')
            ->andWhere('t.id NOT IN(' . implode(",", $arrayIds) . ')')
            ->setParameter('convocatory_id', $convocatory);
        }

        return $qb->getQuery()->getResult();
    }

    public function getStudentsNotINExento($convocatory, $arrayIds,$control)
    {
        
    }


    private function arrayIdsToString($array)
    {
        $arrayIds = Array();

        foreach ($array as $id) {
            $arrayIds[] = $id["id"];
        }

        return $arrayIds;
    }

    public function getAllStudentsWithGroup()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t, u.name, w.convocatory, x.course')
            ->from('AppBundle:Student', 't')
            ->join('t.group', 'u')
            ->join('t.convocatory', 'w')
            ->join('w.schoolYear', 'x');

        return $qb->getQuery()->getArrayResult();
    }

    public function getStudentsBySchoolYearConvocatory($schoolYear, $convocatory)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('t, CONCAT(cc.course, cy.initials, \'-\', u.gr) name, cy.initials cycle, w.convocatory, x.course')
            ->from('AppBundle:Student', 't')
            ->join('t.group', 'u')
            ->join('u.course_cycle', 'cc')
            ->join('cc.cycle', 'cy')
            ->join('t.convocatory', 'w')
            ->join('w.schoolYear', 'x')
            ->where('x.id = :sc_id')
            ->andWhere('w.id = :convocatory_id')
            ->setParameter('sc_id', $schoolYear)
            ->setParameter('convocatory_id', $convocatory);

        return $qb->getQuery()->getArrayResult();
    }
}
